name: gcs_deploy

on:
  workflow_run:
    workflows: ['test-build']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo 'Artifact ID is ${{ github.event.workflow_run.id }}'

      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}

      - name: Display structure of downloaded files
        run: ls -R dist

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'upload-folder'
        if: ${{ github.event_name == 'push' }}
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'dist'
          destination: 'www.sistemasgalacticos.com'
          parent: false
