name: test-build

on: pull_request

# on:
#   pull_request:
#     branches: [main]

permissions:
  issues: write
  pull-requests: write
  statuses: write

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
#   cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Install dependencies
        run: npm install

      - run: echo 'Setup completed'

      - name: Build
        run: npm run build
